'\" t
.\"     Title: aerospace
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.23
.\"      Date: 2025-12-28
.\"    Manual: AeroSpace Manual
.\"    Source: AeroSpace
.\"  Language: English
.\"
.TH "AEROSPACE" "1" "2025-12-28" "AeroSpace" "AeroSpace Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
aerospace \- i3\-like tiling window manager for macOS
.SH "SYNOPSIS"
.sp
.nf
aerospace [\-h|\-\-help] [\-v|\-\-version] <subcommand> [<subcommand\-options>...] [<subcommand\-arguments>...]
.fi
.br
.SH "DESCRIPTION"
.sp
AeroSpace is an i3\-like tiling window manager for macOS
.sp
\fBaerospace\fP command line program is used to manipulate AeroSpace and query its state.
.sp
See \c
.URL "https://nikitabobko.github.io/AeroSpace/commands" "" ""
for available <subcommand> options
.sp
See each <subcommand> individual man page for <subcommand\-options> and <subcommand\-arguments>
.SH "OPTIONS"
.sp
\-h, \-\-help
.RS 4
Print help
.RE
.SH "RESOURCES"
.sp
\fBProject homepage:\fP \c
.URL "https://github.com/nikitabobko/AeroSpace" ""
.br
\fBGuide:\fP \c
.URL "https://nikitabobko.github.io/AeroSpace/guide" ""
.br
.SH "BUGS"
.sp
Bugs can be reported to \c
.URL "https://github.com/nikitabobko/AeroSpace/discussions/categories/potential\-bugs" "" ""
.sp
Maintainers will move verified bugs to \c
.URL "https://github.com/nikitabobko/AeroSpace/issues" "" ""
.SH "LICENSE"
.sp
Copyright \(co 2023 Nikita Bobko
.br
Free use of this software is granted under the terms of the MIT License
.br
You can find the full text of AeroSpace license and its dependencies in the \*(Aqlegal\*(Aq directory of the distributed zip archive.
.SH "AUTHOR"
.sp
Nikita Bobko and contributors