'\" t
.\"     Title: aerospace-reload-config
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.23
.\"      Date: 2025-12-28
.\"    Manual: AeroSpace Manual
.\"    Source: AeroSpace
.\"  Language: English
.\"
.TH "AEROSPACE\-RELOAD\-CONFIG" "1" "2025-12-28" "AeroSpace" "AeroSpace Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
aerospace-reload-config \- Reload currently active config
.SH "SYNOPSIS"
.sp
.nf
aerospace reload\-config [\-h|\-\-help] [\-\-no\-gui] [\-\-dry\-run]
.fi
.br
.SH "DESCRIPTION"
.sp
Reload currently active config
.sp
If the config contains errors they will be printed to stdout, and GUI will open to show the errors.
.SH "OPTIONS"
.sp
\-h, \-\-help
.RS 4
Print help
.RE
.sp
\-\-no\-gui
.RS 4
Don\(cqt open GUI to show error. Only use stdout to report errors
.RE
.sp
\-\-dry\-run
.RS 4
Validate the config and show errors (if any) but don\(cqt reload the config
.RE
.SH "EXIT CODE"
.sp
0
.RS 4
Success. The config is reloaded successfully.
.RE
.sp
non\-zero exit code
.RS 4
Failure. The config contains errors.
.RE
.SH "RESOURCES"
.sp
\fBProject homepage:\fP \c
.URL "https://github.com/nikitabobko/AeroSpace" ""
.br
\fBGuide:\fP \c
.URL "https://nikitabobko.github.io/AeroSpace/guide" ""
.br
.SH "BUGS"
.sp
Bugs can be reported to \c
.URL "https://github.com/nikitabobko/AeroSpace/discussions/categories/potential\-bugs" "" ""
.sp
Maintainers will move verified bugs to \c
.URL "https://github.com/nikitabobko/AeroSpace/issues" "" ""
.SH "LICENSE"
.sp
Copyright \(co 2023 Nikita Bobko
.br
Free use of this software is granted under the terms of the MIT License
.br
You can find the full text of AeroSpace license and its dependencies in the \*(Aqlegal\*(Aq directory of the distributed zip archive.
.SH "AUTHOR"
.sp
Nikita Bobko and contributors