'\" t
.\"     Title: aerospace-focus-monitor
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.23
.\"      Date: 2025-12-28
.\"    Manual: AeroSpace Manual
.\"    Source: AeroSpace
.\"  Language: English
.\"
.TH "AEROSPACE\-FOCUS\-MONITOR" "1" "2025-12-28" "AeroSpace" "AeroSpace Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
aerospace-focus-monitor \- Focus monitor by relative direction, by order, or by pattern
.SH "SYNOPSIS"
.sp
.nf
aerospace focus\-monitor [\-h|\-\-help] [\-\-wrap\-around] (left|down|up|right)
aerospace focus\-monitor [\-h|\-\-help] [\-\-wrap\-around] (next|prev)
aerospace focus\-monitor [\-h|\-\-help] <monitor\-pattern>...
.fi
.br
.SH "DESCRIPTION"
.sp
Focus monitor by relative direction, by order, or by pattern
.SH "OPTIONS"
.sp
\-h, \-\-help
.RS 4
Print help
.RE
.sp
\-\-wrap\-around
.RS 4
Make it possible to wrap around focus
.RE
.SH "ARGUMENTS"
.sp
(left|down|up|right)
.RS 4
Focus monitor in direction relative to the focused monitor
.RE
.sp
(next|prev)
.RS 4
Focus next|prev monitor in order they appear in tray icon
.RE
.sp
<monitor\-pattern>...
.RS 4
Find the first matching monitor and focus it.
Multiple monitor patterns is useful for different monitor configurations.
Monitor patterns follow the same format as in \f(CRworkspace\-to\-monitor\-force\-assignment\fP config option
.RE
.SH "RESOURCES"
.sp
\fBProject homepage:\fP \c
.URL "https://github.com/nikitabobko/AeroSpace" ""
.br
\fBGuide:\fP \c
.URL "https://nikitabobko.github.io/AeroSpace/guide" ""
.br
.SH "BUGS"
.sp
Bugs can be reported to \c
.URL "https://github.com/nikitabobko/AeroSpace/discussions/categories/potential\-bugs" "" ""
.sp
Maintainers will move verified bugs to \c
.URL "https://github.com/nikitabobko/AeroSpace/issues" "" ""
.SH "LICENSE"
.sp
Copyright \(co 2023 Nikita Bobko
.br
Free use of this software is granted under the terms of the MIT License
.br
You can find the full text of AeroSpace license and its dependencies in the \*(Aqlegal\*(Aq directory of the distributed zip archive.
.SH "AUTHOR"
.sp
Nikita Bobko and contributors