'\" t
.\"     Title: aerospace-move-workspace-to-monitor
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.23
.\"      Date: 2025-12-28
.\"    Manual: AeroSpace Manual
.\"    Source: AeroSpace
.\"  Language: English
.\"
.TH "AEROSPACE\-MOVE\-WORKSPACE\-TO\-MONITOR" "1" "2025-12-28" "AeroSpace" "AeroSpace Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
aerospace-move-workspace-to-monitor \- Move workspace to monitor targeted by relative direction, by order, or by pattern.
.SH "SYNOPSIS"
.sp
.nf
aerospace move\-workspace\-to\-monitor [\-h|\-\-help] [\-\-workspace <workspace>] [\-\-wrap\-around] (left|down|up|right)
aerospace move\-workspace\-to\-monitor [\-h|\-\-help] [\-\-workspace <workspace>] [\-\-wrap\-around] (next|prev)
aerospace move\-workspace\-to\-monitor [\-h|\-\-help] [\-\-workspace <workspace>] <monitor\-pattern>...
.fi
.br
.SH "DESCRIPTION"
.sp
Move workspace to monitor targeted by relative direction, by order, or by pattern.
Focus follows the focused workspace, so the workspace stays focused.
.sp
The command fails for workspaces that have monitor force assignment.
.SH "OPTIONS"
.sp
\-h, \-\-help
.RS 4
Print help
.RE
.sp
\-\-wrap\-around
.RS 4
Allows to move workspace between first and last monitors
.RE
.sp
\-\-workspace <workspace>
.RS 4
Act on the specified workspace instead of the focused workspace
.RE
.SH "ARGUMENTS"
.sp
(left|down|up|right)
.RS 4
Move workspace to monitor in direction relative to the focused monitor
.RE
.sp
(next|prev)
.RS 4
Move the workspace to next or prev monitor.
\*(Aqnext\*(Aq or \*(Aqprev\*(Aq monitor is calculated relative to the monitor \f(CR<workspace>\fP currently belongs to.
.RE
.sp
<monitor\-pattern>
.RS 4
Find the first matching monitor and move the workspace there.
Multiple monitor patterns is useful for different monitor configurations.
Monitor patterns follow the same format as in \f(CRworkspace\-to\-monitor\-force\-assignment\fP config option
.RE
.SH "RESOURCES"
.sp
\fBProject homepage:\fP \c
.URL "https://github.com/nikitabobko/AeroSpace" ""
.br
\fBGuide:\fP \c
.URL "https://nikitabobko.github.io/AeroSpace/guide" ""
.br
.SH "BUGS"
.sp
Bugs can be reported to \c
.URL "https://github.com/nikitabobko/AeroSpace/discussions/categories/potential\-bugs" "" ""
.sp
Maintainers will move verified bugs to \c
.URL "https://github.com/nikitabobko/AeroSpace/issues" "" ""
.SH "LICENSE"
.sp
Copyright \(co 2023 Nikita Bobko
.br
Free use of this software is granted under the terms of the MIT License
.br
You can find the full text of AeroSpace license and its dependencies in the \*(Aqlegal\*(Aq directory of the distributed zip archive.
.SH "AUTHOR"
.sp
Nikita Bobko and contributors