'\" t
.\"     Title: aerospace-swap
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.23
.\"      Date: 2025-12-28
.\"    Manual: AeroSpace Manual
.\"    Source: AeroSpace
.\"  Language: English
.\"
.TH "AEROSPACE\-SWAP" "1" "2025-12-28" "AeroSpace" "AeroSpace Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
aerospace-swap \- Swaps the focused window with another window.
.SH "SYNOPSIS"
.sp
.nf
aerospace swap [\-h|\-\-help] [\-\-window\-id <window\-id>] [\-\-swap\-focus]
               [\-\-wrap\-around]
               (left|down|up|right|dfs\-next|dfs\-prev)
.fi
.br
.SH "DESCRIPTION"
.sp
Swaps the focused window with another window.
.sp
The operation is equivalent to dragging a window with the mouse.
.SH "OPTIONS"
.sp
\-h, \-\-help
.RS 4
Print help
.RE
.sp
\-\-window\-id <window\-id>
.RS 4
Act on the specified window instead of the focused window
.RE
.sp
\-\-swap\-focus
.RS 4
Swap focus away from the currently focused window.
By default, this command does not change the focused window.
.RE
.sp
\-\-wrap\-around
.RS 4
Wrap around if the window is at the edge of the workspace (for \f(CR(left|down|up|right)\fP) or the start/end of the depth first order (for \f(CR(dfs\-next|dfs\-prev)\fP).
.RE
.SH "ARGUMENTS"
.sp
(left|down|up|right)
.RS 4
Swaps the focused window with the nearest window in the given direction.
.RE
.sp
(dfs\-next|dfs\-prev)
.RS 4
Swaps the focused window with the next or previous window in the depth\-first order (top\-to\-bottom and left\-to\-right) of windows in the current workspace tree.
.RE
.SH "RESOURCES"
.sp
\fBProject homepage:\fP \c
.URL "https://github.com/nikitabobko/AeroSpace" ""
.br
\fBGuide:\fP \c
.URL "https://nikitabobko.github.io/AeroSpace/guide" ""
.br
.SH "BUGS"
.sp
Bugs can be reported to \c
.URL "https://github.com/nikitabobko/AeroSpace/discussions/categories/potential\-bugs" "" ""
.sp
Maintainers will move verified bugs to \c
.URL "https://github.com/nikitabobko/AeroSpace/issues" "" ""
.SH "LICENSE"
.sp
Copyright \(co 2023 Nikita Bobko
.br
Free use of this software is granted under the terms of the MIT License
.br
You can find the full text of AeroSpace license and its dependencies in the \*(Aqlegal\*(Aq directory of the distributed zip archive.
.SH "AUTHOR"
.sp
Nikita Bobko and contributors