'\" t
.\"     Title: aerospace-move
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.23
.\"      Date: 2025-12-28
.\"    Manual: AeroSpace Manual
.\"    Source: AeroSpace
.\"  Language: English
.\"
.TH "AEROSPACE\-MOVE" "1" "2025-12-28" "AeroSpace" "AeroSpace Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
aerospace-move \- Move the focused window in the given direction
.SH "SYNOPSIS"
.sp
.nf
aerospace move [\-h|\-\-help] [\-\-window\-id <window\-id>] [\-\-boundaries <boundary>] [\-\-boundaries\-action <boundary\-action>] (left|down|up|right)
.fi
.br
.SH "DESCRIPTION"
.sp
Move the focused window in the given direction. See the "Examples" section for more details.
.sp
Deprecated name: \f(CRmove\-through\fP
.SH "OPTIONS"
.sp
\-h, \-\-help
.RS 4
Print help
.RE
.sp
\-\-window\-id <window\-id>
.RS 4
Act on the specified window instead of the focused window
.RE
.sp
\-\-boundaries <boundary>
.RS 4
Defines move boundaries.
.br
\f(CR<boundary>\fP possible values: \f(CR(workspace|all\-monitors\-outer\-frame)\fP.
.br
The default is: \f(CRworkspace\fP
.RE
.sp
\-\-boundaries\-action <boundary\-action>
.RS 4
Defines the behavior when requested to move across the \f(CR<boundary>\fP.
.br
\f(CR<boundary\-action>\fP possible values: \f(CR(stop|fail|create\-implicit\-container)\fP.
.br
The default is: \f(CRcreate\-implicit\-container\fP
.RE
.SH "EXAMPLES"
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.  sp -1
.  IP " 1." 4.2
.\}
Given this layout
.sp
.if n .RS 4
.nf
.fam C
h_tiles
├── window 1 (focused)
└── window 2
.fam
.fi
.if n .RE
.sp
\f(CRmove right\fP will result in the following layout
.sp
.if n .RS 4
.nf
.fam C
h_tiles
├── window 2
└── window 1 (focused)
.fam
.fi
.if n .RE
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.  sp -1
.  IP " 2." 4.2
.\}
Given this layout
.sp
.if n .RS 4
.nf
.fam C
h_tiles
├── window 1
├── window 2 (focused)
└── v_tiles
    ├── window 3
    └── window 4
.fam
.fi
.if n .RE
.sp
\f(CRmove right\fP will result in the following layout
.sp
.if n .RS 4
.nf
.fam C
h_tiles
├── window 1
└── v_tiles
    ├── window 3
    ├── window 2 (focused)
    └── window 4
.fam
.fi
.if n .RE
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 3.\h'+01'\c
.\}
.el \{\
.  sp -1
.  IP " 3." 4.2
.\}
Given this layout
.sp
.if n .RS 4
.nf
.fam C
h_tiles
├── window 1
└── v_tiles
    ├── window 3
    ├── window 2 (focused)
    └── window 4
.fam
.fi
.if n .RE
.sp
\f(CRmove left\fP will result in the following layout
.sp
.if n .RS 4
.nf
.fam C
h_tiles
├── window 1
├── window 2 (focused)
└── v_tiles
    ├── window 3
    └── window 4
.fam
.fi
.if n .RE
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 4.\h'+01'\c
.\}
.el \{\
.  sp -1
.  IP " 4." 4.2
.\}
\fBImplicit container example\fP
.sp
In some cases, \f(CRmove\fP needs to implicitly create a container to fulfill your command.
.sp
Given this layout
.sp
.if n .RS 4
.nf
.fam C
h_tiles
├── window 1
├── window 2 (focused)
└── window 3
.fam
.fi
.if n .RE
.sp
\f(CRmove up\fP will result in the following layout
.sp
.if n .RS 4
.nf
.fam C
v_tiles
├── window 2 (focused)
└── h_tiles
    ├── window 1
    └── window 3
.fam
.fi
.if n .RE
.sp
\f(CRv_tiles\fP is an implicitly created container.
.sp
\fBRemark\fP: If \f(CR\-\-boundaries\fP is set to \f(CRall\-monitors\-outer\-frame\fP and there is a monitor in the \f(CRup\fP direction,
the implicit container isn\(cqt created.
.sp
Instead, \f(CRwindow 2\fP would be moved to the monitor above the current.
.RE
.SH "RESOURCES"
.sp
\fBProject homepage:\fP \c
.URL "https://github.com/nikitabobko/AeroSpace" ""
.br
\fBGuide:\fP \c
.URL "https://nikitabobko.github.io/AeroSpace/guide" ""
.br
.SH "BUGS"
.sp
Bugs can be reported to \c
.URL "https://github.com/nikitabobko/AeroSpace/discussions/categories/potential\-bugs" "" ""
.sp
Maintainers will move verified bugs to \c
.URL "https://github.com/nikitabobko/AeroSpace/issues" "" ""
.SH "LICENSE"
.sp
Copyright \(co 2023 Nikita Bobko
.br
Free use of this software is granted under the terms of the MIT License
.br
You can find the full text of AeroSpace license and its dependencies in the \*(Aqlegal\*(Aq directory of the distributed zip archive.
.SH "AUTHOR"
.sp
Nikita Bobko and contributors