cask "aerospace-dev" do # THE FILE IS GENERATED BY build-brew-cask.sh
  version :latest
  sha256 "57f9c5166b95bb3864cfe9f01d72561b8fd45510f4d7f078eda0e669a0a822e1"

  url "file:///Users/shekhirin/projects/oss/AeroSpace/.release/AeroSpace-v0.0.0-SNAPSHOT.zip"
  name "AeroSpace"
  desc "AeroSpace is an i3-like tiling window manager for macOS"
  homepage "https://github.com/nikitabobko/AeroSpace"
  conflicts_with cask: 'aerospace'

  depends_on macos: ">= :ventura" # macOS 13

  postflight do
    system "xattr -d com.apple.quarantine #{staged_path}/AeroSpace-v0.0.0-SNAPSHOT/bin/aerospace"
    system "xattr -d com.apple.quarantine #{appdir}/AeroSpace.app"
  end

  app "AeroSpace-v0.0.0-SNAPSHOT/AeroSpace.app"
  binary "AeroSpace-v0.0.0-SNAPSHOT/bin/aerospace"

  binary "AeroSpace-v0.0.0-SNAPSHOT/shell-completion/zsh/_aerospace",
      target: "#{HOMEBREW_PREFIX}/share/zsh/site-functions/_aerospace"
  binary "AeroSpace-v0.0.0-SNAPSHOT/shell-completion/bash/aerospace",
      target: "#{HOMEBREW_PREFIX}/etc/bash_completion.d/aerospace"
  binary "AeroSpace-v0.0.0-SNAPSHOT/shell-completion/fish/aerospace.fish",
      target: "#{HOMEBREW_PREFIX}/share/fish/vendor_completions.d/aerospace.fish"

  Dir["#{staged_path}/AeroSpace-v0.0.0-SNAPSHOT/manpage/*"].each { |man| manpage man }
end
